version: '3.7'
services:
  sistema_web:
    container_name: container-kube-noticias
    image: jnlucas/image-phpmysql:latest
    volumes:
      - ./:/var/www/html

    working_dir: /var/www/html/
    ports:
      - "8588:80"
