apiVersion: v1
kind: Service
metadata:
  name: servico-sistema-statefulset
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      nodePort: 31704
  selector:
    name: sistema-pod-statefulset
