apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aplicacao-deployment-noticia
spec:
  template:
    metadata:
      labels:
        name: aplicacao-noticia-pod
    spec:
      containers:
        - name: container-kubernetes-noticia
          image: jnlucas/image-phpmysql:latest
          ports:
            - containerPort: 80
          volumeMounts:
          - name: hostvol
            mountPath: /var/www/html/
      volumes:
        - name: hostvol
          hostPath:
            path: /Users/joaoneves/docker/pedidos/kubernetes/noticias
