apiVersion: v1
kind: Service
metadata:
  name: servico-aplicacao-noticia
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31703
  selector:
    name: aplicacao-noticia-pod
